nome = input("Insira seu nome:")
print("Seu nome maiusculo fica = {}".format(nome.upper()))
print("Seu nome minusculo fica = {}".format(nome.lower()))
ec = float(nome.count(" "))
nc = float(len(nome))
print("O numero de letras no seu nome = {}".format(nc - ec))
fn = nome.split()
print("Seu primeiro nome tem {} letras".format(len(fn[0])))
