a = int(input("Insira o primeiro numero: "))
b = int(input("Insira o segundo numero: "))
c = int(input("Insira o terceiro numero: "))
print("Seu maior numero e = {}".format(max(a, b, c)))
print("Seu menor numero e = {}".format(min(a, b, c)))
